### PR TITLE
Explain a bit more about what's happening

### PR DESCRIPTION
**Pull request by edunham**
Fixes https://github.com/servo/servo-starters/issues/25

### CODE REVIEW

**Comment by Manishearth** [comment]
Not sure if this entirely fixes the issue; "mentored" is more than just having a mentor as mentioned in @jdm's comment. But it's a start.

**Comment by edunham** [comment]
I did a stupid and hand-merged a prior PR, forgot @bors-servo was working here now. So this may fail.

**Comment by KiChjang** [comment]
@bors-servo retry
* wat

**Comment by Manishearth** [comment]
Hm. Homu usually can handle hand-merges.

**Pull request merged**
